// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gwtbslbkiticzghxbbml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd3dGJzbGJraXRpY3pnaHhiYm1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNTg4MTMsImV4cCI6MjA2NDYzNDgxM30.T8_zVldeaIP1TjsLhFieFM-EM6yrCptaeO_PDCB0OZA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);